# Generated by Django 5.0 on 2023-12-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
